trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - name: buildConfiguration
    value: 'release'

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.37
    endpoint: SkillsFundingAgency