trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
    clean: all

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.0
    endpoint: SkillsFundingAgenc

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'

pool:
  name: 'DAS - Continuous Integration Agents'
  demands: LATEST_DOTNET_VERSION -equals 3.1

steps:
- template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'src/SFA.DAS.ProviderCommitments/**/*.csproj'
    noCache: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'src/SFA.DAS.ProviderCommitments/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/SFA.DAS.ProviderCommitments/**/*.UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 'Publish Website'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: |
     azure/**
    TargetFolder: '$(build.artifactstagingdirectory)/publish'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/publish'
