namespace SFA.DAS.ProviderCommitments.Web.RouteValues;

public static class RouteNames
{
    public const string ApprenticesIndex = "apprentices-index";
    public const string DownloadApprentices = "apprentices-download";
    public const string ApprenticeDetail = "apprentice-details";
    public const string ApprenticeReviewApprenticeshipUpdates = "apprentice-review-apprentice-updates";
    public const string ApprenticeViewApprenticeshipUpdates = "apprentice-view-apprentice-updates";
    public const string CancelInProgressChangeOfCircumstance = "cancel-in-progress-change-of-circumstance";
    public const string ChangeEmployer = "apprentice-change-employer";
    public const string ChangeEmployerInform = "apprentice-change-employer-inform";
    public const string ChangeEmployerDetails = "apprentice-change-employer-details";
    public const string ChangeEmployerOverlapAlert = "apprentice-change-employer-overlap-alert";
    public const string ChangeVersion = "change-version";
    public const string ChangeOption = "change-option";
    public const string EditApprenticeship = "edit-apprenticeship";
    public const string ApprenticeSelectEmployer = "apprentice-select-employer";
    public const string ApprenticeConfirmEmployer = "apprentice-confirm-employer";
    public const string ApprenticeSelectDeliveryModel = "apprentice-select-delivery-model";
    public const string ApprenticeStartDate = "apprentice-start-date";
    public const string ApprenticeEndDate = "apprentice-end-date";
    public const string ApprenticePrice = "apprentice-price";
    public const string ApprenticeConfirm = "apprentice-confirm";
    public const string ApprenticeSent = "apprentice-sent";
    public const string ApprenticeDelete = "apprentice-delete";
    public const string ApprenticeTrainingDates = "apprentice-training-dates";
    public const string ConfirmRestart = "confirm-restart";
    public const string RequestRestart = "request-restart";
    public const string UpdateDateLock = "update-datalock";
    public const string UpdateDataLockConfirm = "update-datalock-confirm";
    public const string ChooseCohort = "choose-a-cohort";
    public const string NewCohortSelectEmployer = "new-cohort-select-employer";
    public const string ProviderSignOut = "provider-signout";
    public const string CohortReview = "cohort-review";
    public const string CohortWithTransferSender = "cohort-with-transfer-sender";
    public const string CohortDraft = "cohort-draft";
    public const string CohortWithEmployer = "cohort-with-employer";
    public const string Cohort = "cohort";
    public const string SuccessSaveDraft = "success-save-draft";
    public const string SuccessSendToEmployer = "success-sendto-employer";
    public const string SelectCourse = "add/select-course";
    public const string SetCourseForEdit = "edit/select-course";
    public const string DraftApprenticeshipOverlapAlert = "draft-apprentice-overlap-alert";
    public const string DraftApprenticeshipEdit = "draft-apprenticeship-edit";
    public const string DraftApprenticeshipAddAnother = "draft-apprenticeship-add-another";
    public const string CohortAddApprenticeship = "cohort-add-apprenticeship";
    public const string RecognisePriorLearningData = "recognise-prior-learning-data";
    public const string RecognisePriorLearning = "recognise-prior-learning";
    public const string SelectStandardOption = "select-standard-option";
    public const string SelectLearnerRecordAndCreateCohort = "select-ilr";
    public const string SelectLearnerRecordAndAddToCohort = "select-ilr-to-cohort";
}